In [10]:
import numpy as np
import pandas as pd

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

NumPy: 2.4.6
Pandas: 3.0.6

In [11]:
import numpy as np
import pandas as pd

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

NumPy: 2.4.6
Pandas: 3.0.6

In [12]:
import pandas as pd

train_path = "../data/raw/train_transaction.csv"

df = pd.read_csv(train_path)

print("Shape:", df.shape)
df.head()

Shape: (590540, 394)

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
print(df["isFraud"].value_counts())

print("\nFraud percentage:")
print(df["isFraud"].mean() * 100)

isFraud
0    569877
1     20663
Name: count, dtype: int64

Fraud percentage:
3.4990009144173126

In [14]:
print("Number of columns:", len(df.columns))
print("\nColumn names:")
print(df.columns.tolist())

Number of columns: 394

Column names:
['TransactionID', 'isFraud', 'TransactionDT', 'TransactionAmt', 'ProductCD', 'card1', 'card2', 'card3', 'card4', 'card5', 'card6', 'addr1', 'addr2', 'dist1', 'dist2', 'P_emaildomain', 'R_emaildomain', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13', 'C14', 'D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51', 'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61', 'V62', 'V63', 'V64', 'V65', 'V66', 'V67', 'V68', 'V69', 'V70', 'V71', 'V72', 'V73', 'V74', 'V75', 'V76', 'V77', 'V78', 'V79', 'V80', 'V81', 'V82', 'V83', 'V84', 'V85', 'V86', 'V87', 'V88', 'V89', 'V90', 'V91', 'V92', 'V93', 'V94', 'V95', 'V96', 'V97', 'V98', 'V99', 'V100', 'V101', 'V102', 'V103', 'V104', 'V105', 'V106', 'V107', 'V108', 'V109', 'V110', 'V111', 'V112', 'V113', 'V114', 'V115', 'V116', 'V117', 'V118', 'V119', 'V120', 'V121', 'V122', 'V123', 'V124', 'V125', 'V126', 'V127', 'V128', 'V129', 'V130', 'V131', 'V132', 'V133', 'V134', 'V135', 'V136', 'V137', 'V138', 'V139', 'V140', 'V141', 'V142', 'V143', 'V144', 'V145', 'V146', 'V147', 'V148', 'V149', 'V150', 'V151', 'V152', 'V153', 'V154', 'V155', 'V156', 'V157', 'V158', 'V159', 'V160', 'V161', 'V162', 'V163', 'V164', 'V165', 'V166', 'V167', 'V168', 'V169', 'V170', 'V171', 'V172', 'V173', 'V174', 'V175', 'V176', 'V177', 'V178', 'V179', 'V180', 'V181', 'V182', 'V183', 'V184', 'V185', 'V186', 'V187', 'V188', 'V189', 'V190', 'V191', 'V192', 'V193', 'V194', 'V195', 'V196', 'V197', 'V198', 'V199', 'V200', 'V201', 'V202', 'V203', 'V204', 'V205', 'V206', 'V207', 'V208', 'V209', 'V210', 'V211', 'V212', 'V213', 'V214', 'V215', 'V216', 'V217', 'V218', 'V219', 'V220', 'V221', 'V222', 'V223', 'V224', 'V225', 'V226', 'V227', 'V228', 'V229', 'V230', 'V231', 'V232', 'V233', 'V234', 'V235', 'V236', 'V237', 'V238', 'V239', 'V240', 'V241', 'V242', 'V243', 'V244', 'V245', 'V246', 'V247', 'V248', 'V249', 'V250', 'V251', 'V252', 'V253', 'V254', 'V255', 'V256', 'V257', 'V258', 'V259', 'V260', 'V261', 'V262', 'V263', 'V264', 'V265', 'V266', 'V267', 'V268', 'V269', 'V270', 'V271', 'V272', 'V273', 'V274', 'V275', 'V276', 'V277', 'V278', 'V279', 'V280', 'V281', 'V282', 'V283', 'V284', 'V285', 'V286', 'V287', 'V288', 'V289', 'V290', 'V291', 'V292', 'V293', 'V294', 'V295', 'V296', 'V297', 'V298', 'V299', 'V300', 'V301', 'V302', 'V303', 'V304', 'V305', 'V306', 'V307', 'V308', 'V309', 'V310', 'V311', 'V312', 'V313', 'V314', 'V315', 'V316', 'V317', 'V318', 'V319', 'V320', 'V321', 'V322', 'V323', 'V324', 'V325', 'V326', 'V327', 'V328', 'V329', 'V330', 'V331', 'V332', 'V333', 'V334', 'V335', 'V336', 'V337', 'V338', 'V339']

In [15]:
print(df.dtypes.value_counts())

float64    376
str         14
int64        4
Name: count, dtype: int64

In [16]:
missing = df.isnull().sum()

print("Total missing values:", missing.sum())
print("\nColumns with missing values:")
print(missing[missing > 0].sort_values(ascending=False).head(20))

Total missing values: 95566686

Columns with missing values:
dist2    552913
D7       551623
D13      528588
D14      528353
D12      525823
D6       517353
D9       515614
D8       515614
V157     508595
V163     508595
V162     508595
V161     508595
V158     508595
V153     508595
V138     508595
V155     508595
V154     508595
V149     508595
V148     508595
V147     508595
dtype: int64

In [17]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [18]:
missing = df.isnull().sum()

print("Total missing values:", missing.sum())

print("\nTop 20 columns with missing values:")
print(missing[missing > 0].sort_values(ascending=False).head(20))

Total missing values: 95566686

Top 20 columns with missing values:
dist2    552913
D7       551623
D13      528588
D14      528353
D12      525823
D6       517353
D9       515614
D8       515614
V157     508595
V163     508595
V162     508595
V161     508595
V158     508595
V153     508595
V138     508595
V155     508595
V154     508595
V149     508595
V148     508595
V147     508595
dtype: int64

In [19]:
df[["TransactionAmt", "card1", "addr1"]].describe()

       TransactionAmt          card1          addr1
count   590540.000000  590540.000000  524834.000000
mean       135.027176    9898.734658     290.733794
std        239.162522    4901.170153     101.741072
min          0.251000    1000.000000     100.000000
25%         43.321000    6019.000000     204.000000
50%         68.769000    9678.000000     299.000000
75%        125.000000   14184.000000     330.000000
max      31937.391000   18396.000000     540.000000

In [20]:
df[["TransactionAmt", "card1", "addr1"]].describe()

       TransactionAmt          card1          addr1
count   590540.000000  590540.000000  524834.000000
mean       135.027176    9898.734658     290.733794
std        239.162522    4901.170153     101.741072
min          0.251000    1000.000000     100.000000
25%         43.321000    6019.000000     204.000000
50%         68.769000    9678.000000     299.000000
75%        125.000000   14184.000000     330.000000
max      31937.391000   18396.000000     540.000000

In [21]:
df.groupby("isFraud")["TransactionAmt"].describe()

,count,mean,std,min,25%,50%,75%,max
isFraud,,,,,,,,
0,569877.0,134.511665,239.395078,0.251,43.970,68.5,120.0,31937.391
1,20663.0,149.244779,232.212163,0.292,35.044,75.0,161.0,5191.000

In [22]:
df[["TransactionAmt", "card1", "addr1"]].describe()

       TransactionAmt          card1          addr1
count   590540.000000  590540.000000  524834.000000
mean       135.027176    9898.734658     290.733794
std        239.162522    4901.170153     101.741072
min          0.251000    1000.000000     100.000000
25%         43.321000    6019.000000     204.000000
50%         68.769000    9678.000000     299.000000
75%        125.000000   14184.000000     330.000000
max      31937.391000   18396.000000     540.000000

In [23]:
df["isFraud"].isnull().sum()

np.int64(0)

In [24]:
df["isFraud"].isnull().sum()

np.int64(0)